### 获取客户端IP
GET http://localhost:20080/ip
SECRET: 123456

### 获得所有数据
GET http://localhost:20080/data/
SECRET: 123456

### 将所有数据写入到存储器
PUT http://localhost:20080/data/
SECRET: 123456

### 从存储器中加载所有数据
POST http://localhost:20080/data/
SECRET: 123456

### 添加服务
POST http://localhost:20080/services/
Content-Type: application/x-www-form-urlencoded
SECRET: 123456

id=demo&load_balance=SWRR&meta={"secret":"123456"}

### 重写或创建服务
PUT http://localhost:20080/services/ZGVtbw
Content-Type: application/x-www-form-urlencoded
SECRET: 123456

load_balance=SWRR&meta={"secret":"abcdef"}

### 删除服务
DELETE http://localhost:20080/services/ZGVtbw
SECRET: 123456

### 从服务中获取节点
GET http://127.0.0.1:20080/services/ZGVtbw/select
SECRET: 123456

### 添加节点
POST http://localhost:20080/nodes/
Content-Type: application/x-www-form-urlencoded
SECRET: 123456

service_id=demo&ip=127.0.0.1&port=20180&weight=1&meta={"os": "windows"}

### 重写或创建节点
PUT http://localhost:20080/nodes/ZGVtbw/MTI3LjAuMC4xOjIwMTgw
Content-Type: application/x-www-form-urlencoded
SECRET: 123456

weight=1&ttl=0&meta={"os": "linux"}

### 更新节点的属性
PATCH http://localhost:20080/nodes/ZGVtbw/MTI3LjAuMC4xOjIwMTgw/weight,ttl
Content-Type: application/x-www-form-urlencoded
SECRET: 123456

weight=1&ttl=0

### 节点触活
POST http://localhost:20080/nodes/ZGVtbw/MTI3LjAuMC4xOjIwMTgw
Content-Type: application/x-www-form-urlencoded
SECRET: 123456

### 删除节点
DELETE http://localhost:20080/nodes/ZGVtbw/MTI3LjAuMC4xOjIwMTgw
SECRET: 123456
